import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';
import typography from '@tailwindcss/typography';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}', './src/assets/stitch/**/*.html'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#1d6e25',
        'primary-container': '#415e9a',
        outline: '#747781',
        tertiary: '#005412',
        'surface-container-lowest': '#ffffff',
        'on-secondary-fixed': '#101b30',
        error: '#ba1a1a',
        'on-secondary-container': '#5a647c',
        'on-tertiary-container': '#9bee94',
        'tertiary-fixed': '#a3f69c',
        surface: '#f8f9fa',
        'secondary-fixed-dim': '#bbc6e2',
        'on-tertiary-fixed-variant': '#005312',
        'on-error-container': '#93000a',
        'on-background': '#191c1d',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#264580',
        background: '#f8f9fa',
        'on-primary-fixed': '#001a43',
        'on-tertiary': '#ffffff',
        'on-surface': '#191c1d',
        'on-secondary': '#ffffff',
        'on-primary-container': '#ccd9ff',
        'surface-variant': '#e1e3e4',
        'on-surface-variant': '#444750',
        'primary-fixed': '#d9e2ff',
        'surface-bright': '#f8f9fa',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#afc6ff',
        primary: '#274680',
        'surface-container-low': '#f3f4f5',
        'secondary-container': '#d7e2ff',
        secondary: '#545e76',
        'outline-variant': '#c4c6d1',
        'inverse-on-surface': '#f0f1f2',
        'on-tertiary-fixed': '#002204',
        'on-error': '#ffffff',
        'inverse-primary': '#afc6ff',
        'surface-container-highest': '#e1e3e4',
        'surface-container-high': '#e7e8e9',
        'on-secondary-fixed-variant': '#3c475d',
        'surface-dim': '#d9dadb',
        'inverse-surface': '#2e3132',
        'surface-tint': '#405d99',
        'tertiary-fixed-dim': '#88d982',
        'secondary-fixed': '#d7e2ff',
        'surface-container': '#edeeef',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Work Sans', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [forms, containerQueries, typography],
} satisfies Config;
